### ISSUE TITLE
Teacher Attendance Pie Chart is Hardcoded

### ISSUE THREAD

**Issue by colegarien** [colegarien/SDDTermProject#126]
Nelson recently made and updated so that the main interface for the Teacher Attendance fragment reflected the student's actual number of absences but the Pie Chart is still very, VERY hard-coded.

Rayan, could you please take a look at this as soon as possible so that the Pie Chart accurately reflects the student's attendance.
If you end up having any questions about working with some of the adapters for the database make sure you CC on your emails to Nelson so I can stay up-to-date on your progress.

**Comment by ralhamami** [comment]
Oh yeah, almost forgot that one. It was mainly for testing. I'll take care of it as soon as possible. Thanks for the heads up Cole. :+1:

**Comment by colegarien** [comment]
Hey Rayan, just wanted to check on your status.
Don't forget pull requests are due tonight.

**Comment by ralhamami** [comment]
Thanks for checking in. Yeah, I'm still in the process, but I'll definitely
have it in tonight. I've got the absence part working okay. I just need to
get the attendance part taken care of.

Rayan

**Comment by ralhamami** [comment]
Okay, issue has been fixed, as far as I can tell. 

It took me a long while to figure it out without a lot of attendance data in the system as of yet. However, I believe I've got it to where it is pulling the right data from each respective student for the piechart.
