### ISSUE TITLE
Feature Request: UI design

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#129]
I know this is very last minute, Matt. but @Perrofrijole  and I were looking through the application interface and had some ideas for some of the styling that I think would really make the interface pop. 

For one, an easy change that I for sure want to make is to rename the "In Class Response" buttons on the teacher and the student side both to "Question Center". We feel like this wording better represents the intents of those modules. 

Another change that I would really like to see is instead of having blue text and grey buttons, having blue buttons and white text on those buttons (sort of how the app bar at the top is). I was just thinking that this sort of style would be much more in line with the material design philosophy. 

As I said, I know this is last minute and understand if you arn't able to make these changes. If you can, that would be fantastic. Otherwise, I would like your permission for me to make these changes myself. Let me know what you think!

**Comment by liveyourheart** [comment]
i'm on it.

**Comment by symbyte** [comment]
<3

Let me know if you need my support on this in any way. I'll make myself available any time if you need me.

**Comment by liveyourheart** [comment]
I've got the changes about finished up, I'm just having issues with the
margins for the buttons on devices under 21, happen to have any ideas?
