### ISSUE TITLE
Value in student id retained when hiding the student ID checkbox

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#38]
Whenever you try to log in as a teacher and you uncheck student, if there is a value held in the textbox before it is hidden it will try to read that value and treat the teacher as a student (throws the "student id already exists" error if I just signed up as a student with that ID)

**Comment by nelalison** [comment]
Steven/Matt,

Any objections to removing student id? I don't see any value in having it.
User records will reference a Role record to distinguish between students
and professors, and that's what the checkbox is for. The values I need for
sign up are username, password, first name, last name, email.

**Comment by symbyte** [comment]
We cannot remove student I'd because it is how the teacher is able to know that a student is who they say they are. Ideally the teacher will have a roster that consists of student names and ids. They will reference the student I'd they have against the one that the student is checking in with to verify their identity. It's one of the few pieces of info in the system that I view as mandatory.

**Comment by nelalison** [comment]
I agree with you. But I will need a username from the sign up screen so
that their is a consistent identifier for both student and faculty to log
in.

**Comment by symbyte** [comment]
Can't an email be used as this unique identifier (i.e. as a username)? If I remember right the app is already configured to collect this info

**Comment by nelalison** [comment]
You're right! I will use that.

**Comment by liveyourheart** [comment]
i like the idea of using the email as the user name. Also, I'm not planning on doing anything with gender or phone from the User class.

**Comment by liveyourheart** [comment]
are we already handling ids for teachers?
