### ISSUE TITLE
Email in sign up

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#45]
When entering in an email for sign up, it would be nice if the email input type were used on that EditText to provide easy access on the android keyboard to email centric characters. I believe this was the case before but for some reason nelsons newest updates removed it.

**Comment by liveyourheart** [comment]
this issue was fixed in the mm-add-login branch

**Comment by symbyte** [comment]
Not according to my testing. On your most recent changes that I merged in this morning it still does not show the email friendly keyboard when setting the email field.

**Comment by symbyte** [comment]
I think that there is just a problem with my phones settings in regard to this, when I watched neslon's and your demo video, the feature is working exactly as it should. Sorry about the confusion.
