### ISSUE TITLE
no clear way to log in after creating user

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#50]
There needs to be some detection in place to see if a user has used the application before and if so present them with the login screen instead of the signup screen.

**Comment by liveyourheart** [comment]
my intention was to launch the application directly to the login screen after all bugs were sorted out.  Is this approach suitable?

**Comment by symbyte** [comment]
This approach is fine. If I remember right your login page links in to the sign up page right? Just want to make sure that first time users have a way to sign up
