### ISSUE TITLE
password changing does not work

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#51]
I know that you guys are aware of this, but its going into the issue tracker so that it can be cited as a known issue.

**Comment by symbyte** [comment]
@liveyourheart mentioned it might be a problem with the database, so I am assigning this to @nelalison for now. You guys will likely be working together to fix this one though (as you guys have been doing before)

**Comment by liveyourheart** [comment]
@nelalison I am trying getting a null pointer exception whenever I try to reference the user password.  I looked a little bit into the token that you have created and need a little help figuring out how to get the password.  it crashes whenever I am checking against the current user password or trying to update.  any idea on where to look?

**Comment by nelalison** [comment]
@liveyourheart 
      for security reasons i dont add the password to the token, but if you
look at my newly created remote branch i now have the password reset
functionality all done and its working correctly.

**Comment by symbyte** [comment]
fixed in #68
