### ISSUE TITLE
App crashes when an email address that is already used for another user is used to sign up a new user

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#53]
When signing up as a new user, the user info for a previous user shows up in the user info section if you have signed up as a different user previously.

**Comment by liveyourheart** [comment]
I am having trouble reproducing this bug. Are you logging out before signing in with a new user?  your steps you're taking will be helpful in sorting this out.

**Comment by symbyte** [comment]
I wasnt. Now when I try to logout and then sign up a new user the app just crashes when I press sign up after filling in all of the information.

**Comment by symbyte** [comment]
I tried to reproduce that crash, but was unable too. The second run through of following these steps went fine:
1. Launch app to sign up screen
2. Create user and sign in
3. View user info (is correct)
4. Press logout
5. Press sign up
6. Create user that has all new information and sign in
7. View user info (is correct)

Im going to try a few more things with some variations on this procedure and check back.

**Comment by symbyte** [comment]
Okay, I was able to reproduce the crash. It happens when someone tries to sign up with an email address that has already been used for another user.

**Comment by symbyte** [comment]
Im going to edit the title of the issue to reflect this.

**Comment by nelalison** [comment]
fixed on the cloud

**Comment by symbyte** [comment]
fixed in #59
