### ISSUE TITLE
Partial Credentials at Login Crash

### ISSUE THREAD

**Issue by colegarien** [colegarien/SDDTermProject#62]
**Steps**
1. fill out sign up form, for example email: ppp@ppp.com, pass: ppp
2. On sign-in form only put part of the password such that you enter email: ppp@ppp.com, pass: p
3. Crash

**Log From Crash:**
10-07 21:01:55.594    8967-9383/edu.uco.schambers.classmate I/System.out﹕ Response from Server ....
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ java.io.IOException: No authentication challenges found
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at libcore.net.http.HttpURLConnectionImpl.getAuthorizationCredentials(HttpURLConnectionImpl.java:438)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at libcore.net.http.HttpURLConnectionImpl.processAuthHeader(HttpURLConnectionImpl.java:418)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at libcore.net.http.HttpURLConnectionImpl.processResponseHeaders(HttpURLConnectionImpl.java:367)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:301)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at edu.uco.schambers.classmate.Adapter.ServiceHandlerAsync.makeServiceCall(ServiceHandlerAsync.java:57)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at edu.uco.schambers.classmate.Adapter.ServiceHandlerAsync.doInBackground(ServiceHandlerAsync.java:27)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at edu.uco.schambers.classmate.Adapter.ServiceHandlerAsync.doInBackground(ServiceHandlerAsync.java:15)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-07 21:02:08.868    8967-9585/edu.uco.schambers.classmate W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
10-07 21:02:08.868    8967-8967/edu.uco.schambers.classmate D/AndroidRuntime﹕ Shutting down VM
10-07 21:02:08.868    8967-8967/edu.uco.schambers.classmate W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41843898)
10-07 21:02:08.878    8967-8967/edu.uco.schambers.classmate E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at edu.uco.schambers.classmate.Adapter.AuthAdapter$1.onComplete(AuthAdapter.java:40)
            at edu.uco.schambers.classmate.Adapter.AuthAdapter$1.onComplete(AuthAdapter.java:37)
            at edu.uco.schambers.classmate.Adapter.ServiceHandlerAsync.onPostExecute(ServiceHandlerAsync.java:36)
            at edu.uco.schambers.classmate.Adapter.ServiceHandlerAsync.onPostExecute(ServiceHandlerAsync.java:15)
            at android.os.AsyncTask.finish(AsyncTask.java:631)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5455)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
            at dalvik.system.NativeStart.main(Native Method)
10-07 21:02:10.860    8967-8967/edu.uco.schambers.classmate I/Process﹕ Sending signal. PID: 8967 SIG: 9

**Comment by nelalison** [comment]
Cole,
        I just tried recreating your issue mine works perfectly well. you should try checking out my remote branch and try testing it with that one, if it crashes again record it then email me the video. In my previous pull request I had all that fixed. Thank you

**Comment by symbyte** [comment]
I can also report that I am unable to reproduce this issue.

**Comment by colegarien** [comment]
Hmm, checked out Nelson remote branch and it doesn't seem to be crashing anymore. But I can't seem to sign up or sign in.

I am gonna close this issue for now

**Comment by nelalison** [comment]
Cole,
      Please could you be specific? you cant sign_up or sign_in anymore: is
it stalling or crashing?

**Comment by colegarien** [comment]
I pulled down you remote branch Nelson_changePass
1. After filling out the sign-up form ( name: uuu, email: uuu@uuu.com, pass: uuu, unchecked student box) and pressing the SIGN UP button does nothing, no confirmation, no warnings, doesn't go to sign in page, nothing
2. After pressing SIGN UP a few times I went back to the Login screen and put in the credentials that I just created, email: uuu@uuu.com, pass: uuu then pressed LOGIN, nothing happened, no warnings, no page change, nothing

You know what, I will record a video and put it on drive.

**Comment by colegarien** [comment]
See signin_signup_error.wmv on the drive

If you don't want to bother watching the video, here is the error that came up everytime I pressed SIGN UP and LOGIN:

10-08 15:13:08.250  28604-29033/edu.uco.schambers.classmate W/System.err﹕ java.net.UnknownHostException: Unable to resolve host "classmateapi.azurewebsites.net": No address associated with hostname

**Comment by nelalison** [comment]
Cole,
       I figured out what is going. This problem should be handled by Matt.
Due to the token based authentication from the web service being used,
after a user signup they need to be redirected to the login page to login
for the first time. This way when the user try to login in it will request
the a token from the cloud, which is then saved to the shared preferences
until the user logs out, which then clears the shared preferences. Without
giving the user the chance to login there is no request done and the web
service wont have the opportunity to build the token.

**Comment by symbyte** [comment]
I would also assume that it is possible for the sign up page to also 
complete the same login steps that the login page does in the background 
with the newly created user so that the user can be brought directly to 
the correct interface after signing up and have the authentication token 
created without having to do a repetitive feeling login.
