### ISSUE TITLE
Strange graphics when pressing back button after auto login

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#79]
With the new auto login feature (which is sooooo convenient when testing, thank you for doing this) when pressing the back button after having logged in you see the login screen flash for like a few milli seconds and then it brings you back to the correct interface. This behaviour also has the effect of not allowing you to press back to exit the application, which is what most android users have some to expect to be able to do. 

I assume that these behaviours are happening because, when launching the login fragment, you check immediatly for the token and then prosses a login if the token exists. This is definitely the right way to do this, so I wouldn't change it.

I think that both of these behaviours could be fixed by simply not adding the login screen to the backstack whenever it is launched, since we would never really want a user to navigate back to that screen without first logging out. By fixing it in this way, we sort of kill two birds with one stone because pressing the back button from the initial interface would simply exit out of the app, thus avoiding both the weird graphical flash of the fragment and being "stuck" in the application unless you press the home button. It will also make it where the login screen will only be able to be displayed if someone who is launching the app hasnt yet authenticated _or_ when the logout option has been selected.

Give this a try and let me know what you think. Thanks!

**Comment by colegarien** [comment]
I noticed this too, I believe one possible solution is to have the back button log the user out if they are on the main interface for their type of user.
If this were done it may also be beneficial to show a confirmation dialog box before logging them out
