### ISSUE TITLE
Screen Rotation Causing layered fragments

### ISSUE THREAD

**Issue by colegarien** [colegarien/SDDTermProject#86]
Upon rotating the phone, the sign up screen appears. Pressing the back-button will show the previous fragment that I was in. In some cases if I am on the Teacher Roll Call Fragment the Sign Up screen actually becomes layered on top of the Teacher Roll Call fragment.

I think the easiest solution for this would be to simply force the application to run in portrait style orientation mode.

**Comment by nelalison** [comment]
I think to fix this you have to save the instance of that activity.

**Comment by symbyte** [comment]
More specifically you'd need to restore a saved state of the fragments to be restored when the activity restarts as a result of the aspect changing, overall it is much simpler and widely accepted to simply lock an application to portrait mode

**Comment by colegarien** [comment]
Yeah, that is the way I feel about it.
